#!/usr/bin/env python3
"""
Capture Triton kernels generated by torch.compile() from our PyTorch reference.

This uses PyTorch 2.0+ torch.compile with the Inductor backend to:
1. Compile our backward pass to Triton
2. Dump the generated Triton code to files

Usage:
    # Method 1: Using environment variable
    TORCH_COMPILE_DEBUG=1 python capture_triton.py
    
    # Method 2: Using torch._inductor.config
    python capture_triton.py
    
Output will be in: /tmp/torchinductor_*/
"""

import os
import torch
import torch.nn.functional as F

# Enable Triton code generation debugging
os.environ["TORCH_COMPILE_DEBUG"] = "1"
os.environ["TORCHINDUCTOR_TRACE"] = "1"

# Configure inductor to dump code
import torch._inductor.config as inductor_config
inductor_config.debug = True
inductor_config.trace.enabled = True
inductor_config.trace.graph_diagram = True


def silu_backward(h0: torch.Tensor, da: torch.Tensor) -> torch.Tensor:
    """SiLU backward: da * σ(h0) * (1 + h0 * (1 - σ(h0)))"""
    sig = torch.sigmoid(h0)
    return da * sig * (1.0 + h0 * (1.0 - sig))


def ff_backward_pytorch(
    dy: torch.Tensor,
    x: torch.Tensor,
    w_gate: torch.Tensor,
    w_value: torch.Tensor,
    w_down: torch.Tensor,
    h0: torch.Tensor,
    h1: torch.Tensor,
    a: torch.Tensor,
    g: torch.Tensor,
):
    """
    Pure PyTorch backward pass - will be compiled to Triton.
    """
    # Step 1: dg = dy @ W_down^T
    dg = dy @ w_down.T
    
    # Step 2: dW_down = g^T @ dy
    dw_down = g.T @ dy
    
    # Step 3: da = dg * h1, dh1 = dg * a
    da = dg * h1
    dh1 = dg * a
    
    # Step 4: dh0 = da * SiLU'(h0)
    dh0 = silu_backward(h0, da)
    
    # Step 5: dX = dh0 @ W_gate + dh1 @ W_value
    dx = dh0 @ w_gate + dh1 @ w_value
    
    # Step 6: dW_gate = dh0^T @ X, dW_value = dh1^T @ X
    dw_gate = dh0.T @ x
    dw_value = dh1.T @ x
    
    return dx, dw_gate, dw_value, dw_down


def main():
    print("=" * 70)
    print("  Capturing Triton kernels from torch.compile()")
    print("=" * 70)
    
    device = 'cuda'
    dtype = torch.float32
    
    # Use realistic sizes
    M, N, K = 8, 16384, 3072  # Phi-3 scale
    N_half = N // 2
    
    print(f"\nTest dimensions: M={M}, N={N}, K={K}")
    
    # Create inputs
    torch.manual_seed(42)
    dy = torch.randn(M, K, device=device, dtype=dtype)
    x = torch.randn(M, K, device=device, dtype=dtype)
    w_gate = torch.randn(N_half, K, device=device, dtype=dtype)
    w_value = torch.randn(N_half, K, device=device, dtype=dtype)
    w_down = torch.randn(N_half, K, device=device, dtype=dtype)
    h0 = torch.randn(M, N_half, device=device, dtype=dtype)
    h1 = torch.randn(M, N_half, device=device, dtype=dtype)
    a = F.silu(h0)
    g = a * h1
    
    # Compile the backward function
    print("\nCompiling backward pass with torch.compile()...")
    compiled_backward = torch.compile(
        ff_backward_pytorch,
        backend="inductor",  # Uses Triton
        fullgraph=True,
        mode="default",
    )
    
    # Run compiled version (this triggers code generation)
    print("Running compiled backward (first run generates Triton code)...")
    dx, dw_gate, dw_value, dw_down = compiled_backward(
        dy, x, w_gate, w_value, w_down, h0, h1, a, g
    )
    
    print(f"\nOutputs:")
    print(f"  dx shape: {dx.shape}")
    print(f"  dw_gate shape: {dw_gate.shape}")
    print(f"  dw_value shape: {dw_value.shape}")
    print(f"  dw_down shape: {dw_down.shape}")
    
    # Run again to make sure it's cached
    print("\nRunning again (cached)...")
    dx2, _, _, _ = compiled_backward(
        dy, x, w_gate, w_value, w_down, h0, h1, a, g
    )
    
    print("\n" + "=" * 70)
    print("  Generated Triton code location:")
    print("=" * 70)
    
    # Find the generated code
    import glob
    cache_dirs = glob.glob("/tmp/torchinductor_*")
    if cache_dirs:
        for cache_dir in cache_dirs:
            print(f"\n  Cache directory: {cache_dir}")
            triton_files = glob.glob(f"{cache_dir}/**/*.py", recursive=True)
            for f in triton_files[:10]:  # Show first 10
                print(f"    - {f}")
    else:
        print("\n  Check ~/.cache/torch_inductor/ or /tmp/torchinductor_*/")
    
    print("\n" + "=" * 70)
    print("  Alternative: Use torch._inductor.codecache to inspect")
    print("=" * 70)
    
    try:
        from torch._inductor import codecache
        print(f"\n  Code cache directory: {codecache.cache_dir()}")
    except:
        pass
    
    print("\n✓ Done! Check the directories above for generated Triton code.")


def export_readable_triton():
    """
    Alternative approach: Use torch.export + generate readable code.
    """
    print("\n" + "=" * 70)
    print("  Generating readable Triton code")
    print("=" * 70)
    
    # Use explain mode to see what torch.compile does
    from torch._dynamo import explain
    
    device = 'cuda'
    dtype = torch.float32
    M, N, K = 4, 64, 32
    N_half = N // 2
    
    dy = torch.randn(M, K, device=device, dtype=dtype)
    x = torch.randn(M, K, device=device, dtype=dtype)
    w_gate = torch.randn(N_half, K, device=device, dtype=dtype)
    w_value = torch.randn(N_half, K, device=device, dtype=dtype)
    w_down = torch.randn(N_half, K, device=device, dtype=dtype)
    h0 = torch.randn(M, N_half, device=device, dtype=dtype)
    h1 = torch.randn(M, N_half, device=device, dtype=dtype)
    a = F.silu(h0)
    g = a * h1
    
    explanation = explain(ff_backward_pytorch)(
        dy, x, w_gate, w_value, w_down, h0, h1, a, g
    )
    print(explanation)


if __name__ == "__main__":
    main()
    # Uncomment to also run explain mode:
    # export_readable_triton()

